package views;

import storage.DatabaseInterface;
import storage.FileStoreInterface;
import web.WebRequest;
import web.WebResponse;

public class Upload extends DynamicWebPage
{

	public Upload(DatabaseInterface db,FileStoreInterface fs)
	{
		super(db,fs);
	}

	public boolean process(WebRequest toProcess)
	{
		if(toProcess.path.equalsIgnoreCase("Upload"))
		{
			String stringToSendToWebBrowser = "";
			stringToSendToWebBrowser += "<html>\n";
			stringToSendToWebBrowser += "  <head>\n";
			stringToSendToWebBrowser += "    <meta charset=\"utf-8\">\n";
			stringToSendToWebBrowser += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
			stringToSendToWebBrowser += "    <script type=\"text/javascript\" src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js\"></script>\n";
			stringToSendToWebBrowser += "    <script type=\"text/javascript\" src=\"http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\n";
			stringToSendToWebBrowser += "    <link href=\"http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\"\n";
			stringToSendToWebBrowser += "    rel=\"stylesheet\" type=\"text/css\">\n";
			stringToSendToWebBrowser += "    <link href=\"upload.css\" rel=\"stylesheet\" type=\"text/css\">\n";
			stringToSendToWebBrowser += "    <title>e.mu | Upload</title>\n";
			stringToSendToWebBrowser += "    <link  rel=\"icon\" href=\"\\favicon.png\">\n";
			stringToSendToWebBrowser += "  </head>\n";
			stringToSendToWebBrowser += "  <body>\n";
			stringToSendToWebBrowser += "    <div class=\"cover return-button\">\n";
			stringToSendToWebBrowser += "      <div class=\"navbar\">\n";
			stringToSendToWebBrowser += "        <div class=\"container\">\n";
			stringToSendToWebBrowser += "          <div class=\"navbar-header\">\n";
			stringToSendToWebBrowser += "            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-ex-collapse\">\n";
			stringToSendToWebBrowser += "              <span class=\"sr-only\">Toggle navigation</span>\n";
			stringToSendToWebBrowser += "              <span class=\"icon-bar\"></span>\n";
			stringToSendToWebBrowser += "              <span class=\"icon-bar\"></span>\n";
			stringToSendToWebBrowser += "              <span class=\"icon-bar\"></span>\n";
			stringToSendToWebBrowser += "            </button>\n";
			stringToSendToWebBrowser += "            <a class=\"navbar-brand return-button\" href=\"Independent.html\"><span></span></a>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "          <div class=\"collapse navbar-collapse\" id=\"navbar-ex-collapse\"></div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "      <div class=\"cover-image\" style=\"background-image : url('http://pingendo.github.io/pingendo-bootstrap/assets/blurry/800x600/14.jpg')\"></div>\n";
			stringToSendToWebBrowser += "      <div class=\"container\">\n";
			stringToSendToWebBrowser += "        <div class=\"row\">\n";
			stringToSendToWebBrowser += "          <div class=\"col-md-12 text-center\">\n";
			stringToSendToWebBrowser += "            <h1 class=\"text-inverse\">Upload</h1>\n";
			stringToSendToWebBrowser += "            <p class=\"text-inverse\">Time to shine.\n";
                        stringToSendToWebBrowser += "            <a href=\"enterPage\">Return</a>\n";
			stringToSendToWebBrowser += "              <br>\n";
			stringToSendToWebBrowser += "            </p>\n";
			stringToSendToWebBrowser += "            <form role=\"form\" class=\"text-left\" method=\"GET\" action=\"/FormSubmitted\">\n";
			stringToSendToWebBrowser += "              <div class=\"form-group has-feedback\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"trackName\">Track Title</label>\n";
			stringToSendToWebBrowser += "                <input class=\"form-control\" id=\"trackName\" placeholder=\"Enter title\"\n";
			stringToSendToWebBrowser += "                type=\"text\" name=\"trackName\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputPassword1\">Artist Name</label>\n";
			stringToSendToWebBrowser += "                <input class=\"form-control\" id=\"exampleInputPassword1\"\n";
			stringToSendToWebBrowser += "                placeholder=\"Enter artist\" type=\"text\" name=\"artistName\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\">Album</label>\n";
			stringToSendToWebBrowser += "                <input class=\"form-control\" type=\"text\" placeholder=\"Enter album name\"\n";
			stringToSendToWebBrowser += "                id=\"album\" name=\"album\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Album Art</label>\n";
			stringToSendToWebBrowser += "                <input type=\"text\" class=\"form-control\" placeholder=\"Enter direct URL\"\n";
			stringToSendToWebBrowser += "                id=\"albumThumbnailURL\" name=\"albumThumbnailURL\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Background Art</label>\n";
			stringToSendToWebBrowser += "                <input class=\"form-control\" type=\"text\" placeholder=\"Enter direct URL\"\n";
			stringToSendToWebBrowser += "                id=\"backgroundURL\" name=\"backgroundURL\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Run-time (Seconds)</label>\n";
			stringToSendToWebBrowser += "                <input class=\"form-control\" type=\"text\" placeholder=\"Enter track run-time\"\n";
			stringToSendToWebBrowser += "                id=\"runtime\" name=\"runtime\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Youtube Link</label>\n";
			stringToSendToWebBrowser += "                <input class=\"form-control\" type=\"text\" placeholder=\"Enter youtube link\"\n";
			stringToSendToWebBrowser += "                id=\"youtubeEmbeddedLink\" name=\"youtubeEmbeddedURL\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Purchase Link</label>\n";
			stringToSendToWebBrowser += "                <input class=\"form-control\" type=\"text\" placeholder=\"Enter direct URL\"\n";
			stringToSendToWebBrowser += "                id=\"purchaseLink\" name=\"purchaseLink\">\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Emotion 1 &nbsp;</label>\n";
			stringToSendToWebBrowser += "                <select style=\"color:black\" title=\"Primary Emotion\"\n";
			stringToSendToWebBrowser += "                class=\"control-label\" for=\"exampleInputEmail1\" name=\"primaryEmotion\">\n";
			stringToSendToWebBrowser += "                  <option value=\"love\">Love</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"joy\">Joy</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"surprise\">Surprise</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"anger\">Anger</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"sadness\">Sadness</option>\n";
			stringToSendToWebBrowser += "                </select>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Emotion 2 &nbsp;</label>\n";
			stringToSendToWebBrowser += "                <select style=\"color:black\" title=\"Secondary Emotion\"\n";
			stringToSendToWebBrowser += "                class=\"control-label\" for=\"exampleInputEmail1\" name=\"secondaryEmotion\">\n";
			stringToSendToWebBrowser += "                  <option value=\"affection\">Affection</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"lust-longing\">Lust/Longing</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"cheerfulness\">Cheerfulness</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"contentment\">Contentment</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"pride\">Pride</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"optimism\">Optimism</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"enthrallment\">Enthrallment</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"relief\">Relief</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"irritation\">Irritation</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"exasperation\">Exasperation</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"rage-disgust\">Rage/Disgust</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"envy\">Envy</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"torment\">Torment</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"suffering\">Suffering</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"disappointment\">Disappointment</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"shame\">Shame</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"neglect\">Neglect</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"sympathy\">Sympathy</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"loneliness\">Loneliness</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"horror\">Horror</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"nervousness\">Nervousness</option>\n";
			stringToSendToWebBrowser += "                </select>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"form-group\">\n";
			stringToSendToWebBrowser += "                <label class=\"control-label\" for=\"exampleInputEmail1\">Genre &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</label>\n";
			stringToSendToWebBrowser += "                <select style=\"color:black\"\n";
			stringToSendToWebBrowser += "                title=\"Genre\" class=\"control-label\" for=\"exampleInputEmail1\" name=\"genre\">\n";
			stringToSendToWebBrowser += "                  <option value=\"alternative\">Alternative</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"blues\">Blues</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"childrens-music\">Children's Music</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"classical\">Classical</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"comedy\">Comedy</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"commercial\">Commercial</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"country\">Country</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"dance\">Dance</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"edm\">EDM</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"disney\">Disney</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"easy-listening\">Easy Listening</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"electronic\">Electronic</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"enka\">Enka</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"french-pop\">French Pop</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"german-folk\">German Folk</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"german-pop\">German Pop</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"fitness\">Fitness</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"hip-hop-rap\">Hip-Hop/Rap</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"holiday\">Holiday</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"indie-pop\">Indie Pop</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"industrial\">Industrial</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"inspirational\">Inspirational</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"instrumental\">Instrumental</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"j-pop\">J-Pop</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"jazz\">Jazz</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"k-pop\">K-Pop</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"karaoke\">Karaoke</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"latin\">Latin</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"new-age\">New Age</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"opera\">Opera</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"pop\">Pop</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"randb-soul\">R&amp;B/Soul</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"reggae\">Reggae</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"rock\">Rock</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"singer-songwriter\">Singer/Songwriter</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"spoken-word\">Spoken Word</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"soundtrack\">Soundtrack</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"tex-mex\">Tex-Mex</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"vocal\">Vocal</option>\n";
			stringToSendToWebBrowser += "                  <option value=\"world\">World</option>\n";
			stringToSendToWebBrowser += "                </select>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"text-center\">\n";
			stringToSendToWebBrowser += "                <div class=\"col-md-12\">\n";
			stringToSendToWebBrowser += "                  <button class=\"btn btn-lg btn-primary\" type=\"submit\">Submit</button>\n";
			stringToSendToWebBrowser += "                </div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "              <div class=\"dropdown\">\n";
			stringToSendToWebBrowser += "                <div class=\"dropdown-content\" id=\"myDropdown\"></div>\n";
			stringToSendToWebBrowser += "              </div>\n";
			stringToSendToWebBrowser += "            </form>\n";
			stringToSendToWebBrowser += "          </div>\n";
			stringToSendToWebBrowser += "        </div>\n";
			stringToSendToWebBrowser += "      </div>\n";
			stringToSendToWebBrowser += "    </div>\n";
			stringToSendToWebBrowser += "  </body>\n";
			stringToSendToWebBrowser += "\n";
			stringToSendToWebBrowser += "</html>\n";
			toProcess.r = new WebResponse( WebResponse.HTTP_OK, WebResponse.MIME_HTML, stringToSendToWebBrowser );
			return true;
		}
		return false;
	}

}